---
settings:
  name: Azure NetApp Files
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Azure NetApp Files
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Más información sobre Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Flujo de trabajo inicial
      url: "/task-quick-start.html"
    - title: Configurar una aplicación Microsoft Entra
      url: "/task-set-up-azure-ad.html"
    - title: Crear un entorno de trabajo
      url: "/task-create-working-env.html"
  - title: Utilice Azure NetApp Files
    entries:
    - title: Cree y monte volúmenes
      url: "/task-create-volumes.html"
    - title: Gestione los volúmenes existentes
      url: "/task-manage-volumes.html"
    - title: Quite Azure NetApp Files
      url: "/task-remove-working-env.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
